"""Centralized Vietnamese UI strings. Keep keys ASCII-friendly."""

APP_TITLE = "WGZ Game Updater"

NAV_LIBRARY = "Thư Viện"
NAV_ACCOUNTS = "Share Acc Game"
NAV_SETTINGS = "Cài Đặt"

LIBRARY_HEADER_NAME = "Tên"
LIBRARY_HEADER_GAME = "Game"
LIBRARY_HEADER_VERSION = "Phiên bản"
LIBRARY_HEADER_STATUS = "Trạng thái"
LIBRARY_HEADER_ACTION = "Thao tác"

STATUS_INSTALLED = "Đã cài"
STATUS_UPDATE = "Cần cập nhật"
STATUS_NOT_INSTALLED = "Chưa cài"
STATUS_DOWNLOADING = "Đang tải..."
STATUS_EXTRACTING = "Đang giải nén..."

ACTION_DOWNLOAD = "Tải về"
ACTION_UPDATE = "Cập nhật"
ACTION_OPEN = "Mở"
ACTION_LAUNCH = "Chạy"
ACTION_PAUSE = "Tạm dừng"
ACTION_RESUME = "Tiếp tục"
ACTION_CANCEL = "Hủy"
ACTION_REFRESH = "Làm mới"
ACTION_BROWSE = "Chọn thư mục..."
ACTION_AUTO_LOGIN = "Đăng nhập tự động"

DIALOG_CONFIRM_DELETE_TITLE = "Xác nhận xóa"
DIALOG_NEED_PATH_TITLE = "Chọn đường dẫn"
DIALOG_ERROR_TITLE = "Lỗi"
DIALOG_INFO_TITLE = "Thông báo"
DIALOG_OK = "Đồng ý"
DIALOG_CANCEL = "Hủy"

DOWNLOAD_SPEED_FMT = "{speed} • {percent}% • còn {eta}"
DOWNLOAD_DONE = "Hoàn tất"

ERR_NETWORK = "Lỗi mạng. Vui lòng kiểm tra kết nối."
ERR_NO_DOWNLOAD_URL = "Không tìm thấy link tải."
ERR_EXTRACT = "Lỗi giải nén tệp tin."

SETTINGS_INSTALL_PATH = "Đường dẫn cài đặt"
SETTINGS_GITHUB_TOKEN = "GitHub Token"
SETTINGS_RESET_CACHE = "Xóa cache"
SETTINGS_OPEN_LOG = "Mở thư mục log"
SETTINGS_VERSION = "Phiên bản"
SETTINGS_CHECK_UPDATE = "Kiểm tra cập nhật"

SPLASH_BOOTING = "Đang khởi động..."
SPLASH_CHECKING_VERSION = "Đang kiểm tra phiên bản..."
SPLASH_DOWNLOADING = "Đang tải xuống... {percent}%"
SPLASH_EXTRACTING = "Đang giải nén dữ liệu..."
SPLASH_DONE = "Cập nhật hoàn tất!"
SPLASH_OFFLINE = "Lỗi mạng. Đang chạy chế độ offline..."

# Library grid + detail page
ACTION_LAUNCH_GAME = "🚀 Chạy Game"
ACTION_BACK = "← Quay lại"
ACTION_BROWSE_FOLDER = "Chọn thư mục..."
LABEL_INSTALL_PATH = "Thư mục cài đặt:"
LABEL_PATH_GUIDE = "Hướng dẫn cài đặt:"
LABEL_MOD_SELECT = "Chọn bản cài:"
LABEL_PART_OF = "Phần {current}/{total}"
STATUS_READY = "Sẵn sàng"
STATUS_DONE = "Hoàn tất!"
STATUS_CANCELLED = "Đã hủy"

# Accounts
ACTION_SAVE_DRIVE = "Lưu lên Drive"
ACTION_LOAD_DRIVE = "Tải từ Drive"
ACTION_ADD_ACCOUNT = "Thêm tài khoản"
LABEL_SERVICE = "Dịch vụ:"
LABEL_NICKNAME = "Tên hiển thị:"
LABEL_GAME_TAG = "Game:"
LABEL_ACCOUNTS_COUNT = "{count} tài khoản"
DIALOG_CONFIRM_LOGOUT = "Xác nhận đăng xuất"
MSG_ACCOUNTS_SAVED = "Đã lưu tài khoản lên Drive thành công."
MSG_ACCOUNTS_LOADED = "Đã tải tài khoản từ Drive."
MSG_DRIVE_ERROR = "Lỗi Drive: {error}"
MSG_NO_ACCOUNTS = "Chưa có tài khoản nào."
MSG_SELECT_ACCOUNT = "Hãy chọn một tài khoản."

# Download confirm
DIALOG_DOWNLOAD_CONFIRM = "Xác nhận tải về"
MSG_DOWNLOAD_CONFIRM = "Tải {name} ({parts} phần)?\nDung lượng trống: {free:.1f} GB"
